<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[response: java.lang.IllegalArgumentException: Illegal character in path at index 34: http://172.17.2.102:9100/v1/trade/{tradeId}/cancel]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="370" started-at="2017-12-11T10:31:41Z" finished-at="2017-12-11T10:31:41Z">
    <groups>
      <group name="offline">
        <method signature="TradeTest.cancelTest(java.lang.String, java.lang.String)[pri:0, instance:com.ppdai.TestCases.TradeTest@64729b1e]" name="cancelTest" class="com.ppdai.TestCases.TradeTest"/>
      </group> <!-- offline -->
    </groups>
    <test name="Account" duration-ms="370" started-at="2017-12-11T10:31:41Z" finished-at="2017-12-11T10:31:41Z">
      <class name="com.ppdai.TestCases.TradeTest">
        <test-method status="PASS" signature="classSetup()[pri:0, instance:com.ppdai.TestCases.TradeTest@64729b1e]" name="classSetup" is-config="true" duration-ms="314" started-at="2017-12-11T18:31:41Z" finished-at="2017-12-11T18:31:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classSetup -->
        <test-method status="FAIL" signature="cancelTest(java.lang.String, java.lang.String)[pri:0, instance:com.ppdai.TestCases.TradeTest@64729b1e]" name="cancelTest" duration-ms="9" started-at="2017-12-11T18:31:41Z" data-provider="creatDataList" finished-at="2017-12-11T18:31:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[8]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[cancelTest]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.Interface.service.Assertion.autoAssert(Assertion.java:34)
	at com.ppdai.TestCases.TradeTest.cancelTest(TradeTest.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[response: java.lang.IllegalArgumentException: Illegal character in path at index 34: http://172.17.2.102:9100/v1/trade/{tradeId}/cancel]]>
            </line>
          </reporter-output>
        </test-method> <!-- cancelTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.ppdai.TestCases.TradeTest@64729b1e]" name="tearDown" is-config="true" duration-ms="35" started-at="2017-12-11T18:31:41Z" finished-at="2017-12-11T18:31:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.ppdai.TestCases.TradeTest -->
      <class name="com.Interface.TestData.BeforeSuit">
        <test-method status="PASS" signature="firstSetup(int)[pri:0, instance:com.Interface.TestData.BeforeSuit@23faf8f2]" name="firstSetup" is-config="true" duration-ms="1011" started-at="2017-12-11T18:31:40Z" finished-at="2017-12-11T18:31:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstSetup -->
      </class> <!-- com.Interface.TestData.BeforeSuit -->
    </test> <!-- Account -->
  </suite> <!-- Suite -->
</testng-results>
